<?xml version="1.0"?>
<!-- Mobile 4 wheel robot -->
<robot name="snake_module" xmlns:xacro="http://www.ros.org/wiki/xacro">

	<xacro:property name="PI" value="3.1415926535897931"/>
	
	<xacro:property name="base_height" value="0.02" />
	<xacro:property name="base_width" value="0.2" />
	<xacro:property name="base_depth" value="0.1" />
	
	<xacro:property name="wheel_distance_x" value="0.06" />
	<xacro:property name="jointy_distance" value="0.125" />
	
	<xacro:property name="tool_height" value="0.01" />
	<xacro:property name="tool_width" value="0.1" />
	<xacro:property name="tool_depth" value="0.1" />
	
	
	<xacro:property name="axis_distance" value="0.03" />

	<xacro:macro name="snake_module" params="number rotY rotZ">  

		<joint name="base_footprint_joint${number}" type="fixed">
			<origin xyz="0 0 ${wheel_radius}" rpy="0 0 0" />
			<parent link="base_footprint${number}"/>
			<child link="base_link${number}" />
		</joint>


		<link name="base_link${number}">
			<collision>
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<geometry>
					<mesh filename="package://snakewbot_description/meshes/base_link.stl" />
<!--
					<box size="${base_width} ${base_depth} ${base_height}"/>
-->
				</geometry>
			</collision>

			<visual>
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<geometry>
					<mesh filename="package://snakewbot_description/meshes/base_link.stl" />
<!--
					<box size="${base_width} ${base_depth} ${base_height}"/>
-->
				</geometry>
				<material name="grey2"/>
			</visual>

			<inertial>
				<origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
				<mass value="1"/>
				<inertia
					ixx="0.001" ixy="0.0" ixz="0.0"
					iyy="0.001" iyz="0.0"
					izz="0.001"/>
			</inertial>
		</link>
		<gazebo reference="base_link${number}">
			<material>Gazebo/White</material>
		</gazebo>


		<snake_wheel twheel="front_right${number}" parent="base_link${number}" 
			pos="${wheel_distance_x} -${base_depth/2 + wheel_depth/2} 0" 
			rot="${PI/2} 0 0"/>
		<snake_wheel twheel="front_left${number}" parent="base_link${number}" 
			pos="${base_width/2 - wheel_radius} ${base_depth/2 + wheel_depth/2} 0" 
			rot="${PI/2} 0 0"/>
		<snake_wheel twheel="back_right${number}" parent="base_link${number}" 
			pos="-${base_width/2 - wheel_radius} -${base_depth/2 + wheel_depth/2} 0" 
			rot="${PI/2} 0 0"/>
		<snake_wheel twheel="back_left${number}" parent="base_link${number}" 
			pos="-${base_width/2 - wheel_radius} ${base_depth/2 + wheel_depth/2} 0" 
			rot="${PI/2} 0 0"/>


		<joint name="joint_y${number}" type="revolute">
			<parent link="base_footprint${number}"/>
			<child link="link_y${number}"/>
			<origin xyz="${jointy_distance} 0 ${wheel_radius}" rpy="0 ${rotY} 0" /> 
			<axis xyz="0 1 0" rpy="0 0 0" />
			<limit lower="-${PI/4}" upper="${PI/4}" effort="100" velocity="100"/>
			<joint_properties damping="0.0" friction="0.0"/>
		</joint>

		<link name="link_y${number}">
			<collision>
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<geometry>
					<mesh filename="package://snakewbot_description/meshes/crossaxis.stl" />
				</geometry>
			</collision>

			<visual>
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<geometry>
					<mesh filename="package://snakewbot_description/meshes/crossaxis.stl" />
				</geometry>
				<material name="grey2"/>
			</visual>

			<inertial>
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<mass value="0.001"/>
				<inertia
					ixx="0.001" ixy="0.0" ixz="0.0"
					iyy="0.001" iyz="0.0"
					izz="0.001"/>
			</inertial>
		</link>
		<gazebo reference="link_y${number}">
			<material>Gazebo/Grey</material>
		</gazebo>
			
		<joint name="joint_z${number}" type="revolute">
			<parent link="link_y${number}"/>
			<child link="link_z${number}"/>
			<origin xyz="0 0 0" rpy="0 0 ${rotZ}" /> 
			<axis xyz="0 0 1" rpy="0 0 0" />
			<limit lower="-${PI/6}" upper="${PI/6}" effort="100" velocity="100"/>
			<joint_properties damping="0.0" friction="0.0"/>
		</joint>

		<link name="link_z${number}">
			<collision>
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<geometry>
					<mesh filename="package://snakewbot_description/meshes/joint1_fix.stl" />
				</geometry>
			</collision>

			<visual>
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<geometry>
					<mesh filename="package://snakewbot_description/meshes/joint1_fix.stl" />
				</geometry>
				<material name="grey2"/>
			</visual>

			<inertial>
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<mass value="0.001"/>
				<inertia
					ixx="0.001" ixy="0.0" ixz="0.0"
					iyy="0.001" iyz="0.0"
					izz="0.001"/>
			</inertial>
		</link>
		<gazebo reference="link_z${number}">
			<material>Gazebo/Grey</material>
		</gazebo>
  
		<joint name="joint_base${number}" type="fixed">
			<origin xyz="${jointy_distance} 0 -${wheel_radius}" rpy="0 0 0" />
			<parent link="link_z${number}"/>
			<child link="base_footprint${number+1}" />
		</joint>

		<link name="base_footprint${number+1}">
			<inertial>
				<mass value="0.0001" />
				<origin xyz="0 0 0" />
				<inertia 
					ixx="0.0001" ixy="0.0" ixz="0.0"
					iyy="0.0001" iyz="0.0" 
					izz="0.0001" />
			</inertial>

			<visual>
				<origin xyz="0 0 0" rpy="0 0 0" />
				<geometry>
					<box size="0.001 0.001 0.001" />
				</geometry>
				<material name="red"/>
			</visual>
		</link>
	
	</xacro:macro>
</robot>
