<?xml version="1.0"?>
<!-- Snake robot -->
<robot name="snakewbot" xmlns:xacro="http://www.ros.org/wiki/xacro">
	
	<xacro:include filename="$(find snakewbot_description)/urdf/snake_module.urdf.xacro" />	 
	<xacro:include filename="$(find snakewbot_description)/urdf/materials.xacro" />
	<xacro:include filename="$(find snakewbot_description)/urdf/wheel.urdf.xacro" /> 
	
  <!-- BASE-FOOTPRINT -->
  <!-- base_footprint is a fictitious link(frame) that is on the ground right below base_link origin -->	
	<link name="base_footprint1">
		<inertial>
            <mass value="0.0001" />
            <origin xyz="0 0 0" />
            <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
                iyy="0.0001" iyz="0.0" 
                izz="0.0001" />
        </inertial>

        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="0.001 0.001 0.001" />
<!--
				<mesh filename="package://custombot_description/meshes/joint1_fix.stl" />
-->
            </geometry>
            <material name="red"/>
        </visual>
    </link>

    <snake_module number="1" n2="2" rotY="0" rotZ="0"/>
    <snake_module number="2" n2="3" rotY="0" rotZ="0"/>
    <snake_module number="3" n2="4" rotY="0" rotZ="0"/>
    <snake_module number="4" n2="5" rotY="0" rotZ="0"/>
    <snake_module number="5" n2="6" rotY="0" rotZ="0"/>
    <snake_module number="6" n2="7" rotY="0" rotZ="0"/>
    <snake_module number="7" n2="8" rotY="0" rotZ="0"/>
    <snake_module number="8" n2="9" rotY="0" rotZ="0"/>
    

  <gazebo>
    <plugin name="skid_steer_drive_controller1" filename="libgazebo_ros_skid_steer_drive.so">
      <alwaysOn>true</alwaysOn>
      <updateRate>100.0</updateRate>
      <leftFrontJoint>front_left1_wheel_joint</leftFrontJoint>
      <rightFrontJoint>front_right1_wheel_joint</rightFrontJoint>
      <leftRearJoint>back_left1_wheel_joint</leftRearJoint>
      <rightRearJoint>back_right1_wheel_joint</rightRearJoint>
      <wheelSeparation>${2*base_y_origin_to_wheel_origin}</wheelSeparation>
      <wheelDiameter>${2*wheel_radius}</wheelDiameter>
      <torque>35</torque>
      <broadcastTF>1</broadcastTF>
      <odometryFrame>map</odometryFrame>
      <commandTopic>/cmd_vel</commandTopic>
      <odometryTopic>odom</odometryTopic>
      <robotBaseFrame>base_footprint1</robotBaseFrame>
    </plugin>
  </gazebo>



</robot>
