<?xml version="1.0"?>
<robot name="snake_module" xmlns:xacro="http://www.ros.org/wiki/xacro">
	
  <!-- PROPERTY LIST -->
  <!--All units in m-kg-s-radians unit system -->
  <property name="M_PI" value="3.1415926535897931" />

  <!-- Main Body-base -->
  <property name="base_x_size" value="0.2" /> 
  <property name="base_y_size" value="0.1" /> 
  <property name="base_z_size" value="0.02" />
  <property name="base_mass" value="1" /> <!-- in kg-->
  
  <property name="joint_distance" value="0.125" />
  
  <!--Inertial macros for the box and cylinder. Units are kg*m^2-->
  <macro name="box_inertia" params="m x y z">
    <inertia  ixx="${m*(y*y+z*z)/12}" ixy = "0" ixz = "0"
              iyy="${m*(x*x+z*z)/12}" iyz = "0"
              izz="${m*(x*x+z*z)/12}" /> 
  </macro>
  
  
  <xacro:macro name="snake_module" params="number rotY rotZ">  

	<joint name="base_footprint_joint${number}" type="fixed">
		<origin xyz="0 0 ${wheel_radius - base_z_origin_to_wheel_origin}" rpy="0 0 0" />
		<parent link="base_footprint${number}"/>
		<child link="base_link${number}" />
	</joint>
	
	<!-- BASE-LINK -->
	<!--Actual body/chassis of the robot-->
	<link name="base_link${number}">
		<inertial>
			<mass value="${base_mass}" />
			<origin xyz="0 0 0" />
			<!--The 3x3 rotational inertia matrix. -->
			<box_inertia  m="${base_mass}" x="${base_x_size}" y="${base_y_size}" z="${base_z_size}"/> 
		</inertial>    
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry>
				<mesh filename="package://snakewbot_description/meshes/base_link.stl" />
			</geometry>
			<material name="orange" />
		</visual>  
		<collision>
			<origin xyz="0 0 0" rpy="0 0 0 " />
			<geometry>
				<mesh filename="package://snakewbot_description/meshes/base_link.stl" />
			</geometry>
		</collision>     
	</link>
	
	<gazebo reference="base_link${number}">
		<material>Gazebo/Orange</material>
		<turnGravityOff>false</turnGravityOff>
	</gazebo>
	
	<!-- WHEELs -->
	<snake_wheel fb="front" lr="right${number}" parent="base_link${number}" translateX="1" translateY="-1" flipY="-1"/>
	<snake_wheel fb="front" lr="left${number}" parent="base_link${number}" translateX="1" translateY="1" flipY="-1"/>
	<snake_wheel fb="back" lr="right${number}" parent="base_link${number}" translateX="-1" translateY="-1" flipY="-1"/>
	<snake_wheel fb="back" lr="left${number}" parent="base_link${number}" translateX="-1" translateY="1" flipY="-1"/>	
	
	
	<joint name="joint_y${number}" type="revolute">
		<parent link="base_footprint${number}"/>
		<child link="link_y${number}"/>
		<origin xyz="${joint_distance} 0 ${wheel_radius}" rpy="0 ${rotY} 0" /> 
		<axis xyz="0 1 0" rpy="0 0 0" />
		<limit lower="-${M_PI/4}" upper="${M_PI/4}" effort="100" velocity="100"/>
		<joint_properties damping="0.0" friction="0.0"/>
	</joint>

	<link name="link_y${number}">
		<collision>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<geometry>
				<mesh filename="package://snakewbot_description/meshes/crossaxis.stl" />
			</geometry>
		</collision>

		<visual>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<geometry>
				<mesh filename="package://snakewbot_description/meshes/crossaxis.stl" />
			</geometry>
			<material name="grey2"/>
		</visual>

		<inertial>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<mass value="0.001"/>
			<inertia
				ixx="0.001" ixy="0.0" ixz="0.0"
				iyy="0.001" iyz="0.0"
				izz="0.001"/>
		</inertial>
	</link>
	<gazebo reference="link_y${number}">
		<material>Gazebo/Grey</material>
	</gazebo>
			
	<joint name="joint_z${number}" type="revolute">
		<parent link="link_y${number}"/>
		<child link="link_z${number}"/>
		<origin xyz="0 0 0" rpy="0 0 ${rotZ}" /> 
		<axis xyz="0 0 1" rpy="0 0 0" />
		<limit lower="-${M_PI/6}" upper="${M_PI/6}" effort="100" velocity="100"/>
		<joint_properties damping="0.0" friction="0.0"/>
	</joint>

	<link name="link_z${number}">
		<collision>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<geometry>
				<mesh filename="package://snakewbot_description/meshes/joint1_fix.stl" />
			</geometry>
		</collision>

		<visual>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<geometry>
				<mesh filename="package://snakewbot_description/meshes/joint1_fix.stl" />
			</geometry>
			<material name="grey2"/>
		</visual>

		<inertial>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<mass value="0.001"/>
			<inertia
				ixx="0.001" ixy="0.0" ixz="0.0"
				iyy="0.001" iyz="0.0"
				izz="0.001"/>
		</inertial>
	</link>
	<gazebo reference="link_z${number}">
		<material>Gazebo/Grey</material>
	</gazebo>
  
	<joint name="joint_base${number}" type="fixed">
		<origin xyz="${joint_distance} 0 -${wheel_radius}" rpy="0 0 0" />
		<parent link="link_z${number}"/>
		<child link="base_footprint${number+1}" />
	</joint>

	<link name="base_footprint${number+1}">
		<inertial>
			<mass value="0.0001" />
			<origin xyz="0 0 0" />
			<inertia 
				ixx="0.0001" ixy="0.0" ixz="0.0"
				iyy="0.0001" iyz="0.0" 
				izz="0.0001" />
		</inertial>
			<visual>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry>
				<box size="0.001 0.001 0.001" />
			</geometry>
			<material name="red"/>
		</visual>
	</link>
	
  </xacro:macro>
</robot>
	
	
	
